<?php /** @var \Stanislavz\Chat\Block\ChatForm $block */ ?>
<?php $lastMessages = $block->getLastMessages() ?>
<div class="chat-wrapper"
     id="chat-wrapper"
     data-mage-init='{"chatModal":{}}'
     style="display: none"
>
    <div id="message-wrapper">
        <ul class="message-list">
            <?php /** @var \Stanislavz\Chat\Model\Message $message */
            foreach ($lastMessages as $message) : ?>
            <li class="message-item <?= $block->escapeHtmlAttr($message->getAuthorType()) ?>">
                <p class="message"><?= $block->escapeHtml($message->getMessage()) ?></p>
                <p class="name"><?= $block->escapeHtml($message->getAuthorName()) ?></p>
                <p class="time"><?= $block->escapeHtml($message->getCreatedAt()) ?></p>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <form action="javascript:void(0)"
          method="post"
          class="chat-form"
          id="chat-form"
          data-mage-init='{
            "validate": {},
            "chatFormWidget":{
                "action": "<?= $block->escapeUrl($block->getFormAction()) ?>"
            }
          }'
    >
        <div class="flex-wrap">
            <div class="field name required">
                <div class="control">
                    <textarea name="message"
                              class="textarea required text"
                              id="customer_message"
                    ></textarea>
                    <label for="customer_message" class="label"><?= $block->escapeHtml(__('Question')) ?></label>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <input type="hidden" name="author_type" id="author_type" value="customer"/>
                    <input type="hidden"
                           name="chat_hash"
                           id="chat_hash"
                           value="<?= $block->escapeHtmlAttr($block->getChatHashCookie()) ?>"
                    />
                    <button type="submit"
                            id="message-submit"
                            title="<?= $block->escapeHtmlAttr(__('Send')) ?>"
                            class="action submit primary">
                        <span><?= $block->escapeHtml(__('Send')) ?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
