<?php /** @var \Stanislavz\Chat\Block\ChatForm $block */ ?>
<div class="chat-wrapper"
     id="chat-wrapper"
     data-mage-init='{"chatModal":{}}'
     style="display: none"
>
    <div id="message-wrapper">
        <ul class="message-list"></ul>
    </div>
    <form action="javascript:void(0)"
          method="post"
          class="chat-form"
          id="chat-form"
          data-mage-init='{
            "validate": {},
            "chatFormWidget":{
                "action": "<?= $block->escapeUrl($block->getFormAction()) ?>"
            }
          }'
    >
        <div class="flex-wrap">
            <div class="field name required">
                <div class="control">
                    <textarea name="message"
                              class="textarea required text"
                              id="customer_message"
                    ></textarea>
                    <label for="customer_message" class="label"><?= $block->escapeHtml(__('Question')) ?></label>
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden"
                           name="store_id"
                           value="<?= $block->escapeHtml($block->getStoreId()) ?>"
                    />
                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <button type="submit"
                            id="message-submit"
                            title="<?= $block->escapeHtmlAttr(__('Send')) ?>"
                            class="action submit primary">
                        <span><?= $block->escapeHtml(__('Send')) ?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
